name: tests

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_call:

permissions: {}

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_VERSION: 0.12.20

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to check out the repository
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv and Python ${{ matrix.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ matrix.PYTHON_VERSION }}
          enable-cache: "false"

      - name: Test the library
        run: uv run --locked poe check-all
