name: tests

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_call:

permissions: {}

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_VERSION: 0.12.20

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to check out the repository
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: "true"
          persist-credentials: false

      - name: Install uv and Python ${{ matrix.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ matrix.PYTHON_VERSION }}
          enable-cache: "false"

      - name: Test the library
        run: uv run --locked poe check-all
