name: wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    name: build-wheels
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to check out the repository
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11

      - name: Build wheels
        run: pip wheel --no-deps -w wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: typeline-wheels
          path: ./wheelhouse/typeline*.whl
          if-no-files-found: error
