name: wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build wheels
        run: pip wheel --no-deps -w wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/typeline*.whl
          if-no-files-found: error
